### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by 0x0000null** [0x0000null/project1-0x0000null#1]
* [x] Create GitHub repository
* [x] Setup PostgreSQL database
* [x] Get Goodreads API key
* [x] Frontend:
    * [x] Template
    * [x] Registration
    * [x] Login
    * [x] Logout
    * [x] Search
    * [x] Book Page
    * [x] Review Submission
    * [x] Goodreads Review Data
* [x] Backend:
    * [x] Registration
    * [x] Login
    * [x] Logout
    * [x] Import
    * [x] Search
    * [x] Book Page
    * [x] Review Submission
    * [x] Goodreads Review Data
    * [x] API Access
* [x] Writeup in readme
